name: CI/CD

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: out
          jekyll: false
          fqdn: mitherz.tech
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
